version: "3.2"

services:
  # Enable docker to auto-run any architecture image using qemu
  #     docker run --rm --privileged multiarch/qemu-user-static:register --reset
  multiarch:
    container_name: multiarch
    image: multiarch/qemu-user-static:register
    privileged: true
    restart: "no"
    deploy:
      mode: global

  rpi-ethereum:
    build: .
    image: sofwerx/rpi-ethereum
    volumes:
      - ./outputs/:/outputs/
    command: cp -r /usr/local/bin/ /outputs/ 
